### ISSUE TITLE
Handle stdin EOF in start_input_loop to prevent 100% CPU spin

### ISSUE THREAD

**Issue by KBluePurple** [Shadowner/Infrarust#53]
Hello,

I've encountered a significant platform-specific issue with CPU usage. The process runs at 100% on a single core on NixOS, whereas the same configuration on Windows shows negligible CPU usage.

### Environment

  * **OS (Linux):** NixOS 24.05 (managed by the service definition below)
  * **Kernel:** `6.12.31`
  * **App Version:** `1.4.0` (Installed from crates.io via NixOS derivation)

### Actual Behavior

The process consistently causes a single CPU core to run at 100% utilization on NixOS.

![Image](https://github.com/user-attachments/assets/7523baa5-e297-4ee3-a6c8-7bb171cad76e) 
![Image](https://github.com/user-attachments/assets/9f899bdc-ea81-42cf-999f-e7ceb9e1ec5d) 

### Expected Behavior

CPU usage on NixOS should be low and comparable to the usage on Windows (near 0-5%), as the task is not expected to be CPU-intensive with this configuration.

For comparison, here is the usage on Windows with the exact same `config` and `proxy` files:

```yaml
bind: "0.0.0.0:25565"
keepAliveTimeout: 30s

filters:
  rateLimiter:
    requestLimit: 10
    windowLength: 1s


file_provider:
  proxies_path:
    - "./proxies"
  watch: false

logging:
  debug: true
  use_color: true
  use_icons: true
  show_timestamp: true
  time_format: "%Y-%m-%d %H:%M:%S"
  show_target: true
  show_fields: true
  template: "{timestamp} [{level}] {message}"

  min_level: "debug"
  
  field_prefixes:
    fields: "\n\t\t\t"
    target: "\n\t\t "

proxy_protocol:
  enabled: true
  receive_enabled: true
  receive_timeout_secs: 5
  receive_allowed_versions: [1, 2]

cache:
  status_ttl_seconds: 30
  max_status_entries: 1000

motds:
  unreachable:
    version_name: "Unreachable"
    protocol_version: 760
    max_players: 100
    online_players: 0
    text: "§c§lServer Unreachable§r\n§7 Please try again later"
    favicon: ""
```

```yaml
domains:
  - "-"
  - "-"
addresses:
  - "-"
sendProxyProtocol: false
proxyMode: passthrough

server_manager:
  provider_name: Local
  server_id: "local_server"
  empty_shutdown_time: 300
  local_provider:
    executable: "bash"
    working_dir: "/var/lib/infrarust/servers/minecraft-server/data"
    args:
      - "/var/lib/infrarust/servers/minecraft-server/data/run.sh"
    startup_string: 'For help, type "help"'

motds: 
  # Server is unreachable/offline
  unreachable:
    enabled: true
    text: "-"
    version_name: "-"
    max_players: 100
    online_players: 0
    # Uses embedded favicon in base64
    favicon: "-"

  # Server is online and running
  online:
    enabled: true
    version_name: "-"
    protocol_version: 763
    text: "-"
    favicon: "-"

  # Server is starting up
  starting:
    enabled: true
    text: "-"
    version_name: "-"
    max_players: 100
    online_players: 0

  # Server is offline/sleeping
  offline:
    enabled: true
    text: "-"
    version_name: "-"
    max_players: 100
    online_players: 0
    favicon: "-"

  # Server is shutting down with countdown
  shutting_down:
    enabled: true
    text: "-" # ${seconds_remaining} will be replaced with the actual countdown
    version_name: "-"
    max_players: 100
    online_players: 0
    protocol_version: 763

  # Server crashed
  crashed:
    enabled: true
    text: "-"
    version_name: "-"
    max_players: 100
    online_players: 0
    favicon: "./icons/error-icon.png"  # Relative path example

  # Server is stopping gracefully
  stopping:
    enabled: true
    text: "-"
    version_name: "-"
    max_players: 100
    online_players: 0
    protocol_version: 763

  # Unable to get server status
  unable_status:
    enabled: true
    text: "-"
    version_name: "-"
    max_players: 100
    online_players: 0
    protocol_version: 763
```

### NixOS Service Configuration

This is the NixOS service definition used to run the application, which fully describes the execution environment.

```nix
{ config, pkgs, lib, ... }:

let
  moduleDir = builtins.dirOf ./.;
  infrarustConfigBase = "${moduleDir}/infrarust/config";

  infrarustConfigData = pkgs.runCommand "infrarust-config-data" {
  } ''
    mkdir -p $out
    cp "${infrarustConfigBase}/config.yaml" $out/config.yaml

    mkdir -p $out/proxies
    if [ -d "${infrarustConfigBase}/proxies" ] && [ "$(ls -A "${infrarustConfigBase}/proxies")" ]; then
      echo "INFO: Copying proxies directory contents from ${infrarustConfigBase}/proxies"
      cp -Lr "${infrarustConfigBase}/proxies/"* $out/proxies/
    else
      echo "INFO: Proxies directory not found or is empty at ${infrarustConfigBase}/proxies. $out/proxies will be empty."
    fi
  '';

  infrarustPkg = let
    crateVersion = "1.4.0";
  in pkgs.rustPlatform.buildRustPackage {
    pname = "infrarust";
    version = crateVersion;
    cargoHash = "sha256-GzH3xB3oKVKvju4ttW94Pu/giU91CuJhzyXJp04S3Ng=";

    src = pkgs.fetchCrate {
      crateName = "infrarust";
      version = crateVersion;
      hash = "sha256-blxBkN4WgpeCBDzQNfns31RT4djKAp5GrNCWp3zfEOQ=";
    };

    meta = with lib; {
      description = "Infrarust server application fetched from crates.io";
    };
  };

in
{
  systemd.services.infrarust = {
    description = "Infrarust Service";
    wantedBy = [ "multi-user.target" ];
    after = [ "network.target" "docker.service" ];

    serviceConfig = {
      User = "infrarust";
      Group = "infrarust";
      SupplementaryGroups = [ "docker" ];

      StateDirectory = "infrarust";
      WorkingDirectory = "/var/lib/infrarust";

      ExecStart = ''
        ${infrarustPkg}/bin/infrarust \
          --config-path "[YOUR_CONFIG_PATH]/config.yaml" \
          --proxies-path "[YOUR_CONFIG_PATH]/proxies/"
      '';
      
      Environment = [
        "PATH=${lib.makeBinPath [ pkgs.jdk17 pkgs.coreutils pkgs.bash ]}"
      ];

      Restart = "always";
      RestartSec = "10s";
      StandardOutput = "journal";
      StandardError = "journal";
    };
  };

  users.users.infrarust = {
    isNormalUser = true;
    group = "infrarust";
    home = "/var/lib/infrarust";
  };
  users.groups.infrarust = {};
}
```
